from pydantic import BaseModel, ConfigDict, Field


# ============================================================
# Request
# ============================================================

class RiskRequest(BaseModel):
    """
    Request for analyzing a single asset.
    """

    asset: str = Field(
        ...,
        min_length=1,
        description="Asset value (e.g. api.example.com).",
    )


# ============================================================
# Response
# ============================================================

class RiskResponse(BaseModel):
    """
    Risk analysis generated by the AI.
    """

    model_config = ConfigDict(
        from_attributes=True,
    )

    asset: str

    risk_level: str

    summary: str

    findings: list[str]

    recommendations: list[str]