"""initial schema

Revision ID: ed1099496357
Revises: 
Create Date: 2026-06-28 11:25:12.572010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed1099496357'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('type', sa.Enum('domain', 'subdomain', 'ip_address', 'service', 'certificate', 'technology', name='asset_type_enum'), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('active', 'stale', 'archived', name='asset_status_enum'), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('first_seen', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('type', 'value', name='uq_asset_type_value')
    )
    op.create_index('ix_asset_value', 'assets', ['value'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_asset_id', sa.UUID(), nullable=False),
    sa.Column('target_asset_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.Enum('parent', 'covers', 'resolves_to', 'hosted_on', 'powered_by', name='relation_type_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_asset_id', 'target_asset_id', 'relation_type', name='uq_relationship')
    )
    op.create_index('ix_relationship_source', 'relationships', ['source_asset_id'], unique=False)
    op.create_index('ix_relationship_target', 'relationships', ['target_asset_id'], unique=False)
    op.create_index('ix_relationship_type', 'relationships', ['relation_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_relationship_type', table_name='relationships')
    op.drop_index('ix_relationship_target', table_name='relationships')
    op.drop_index('ix_relationship_source', table_name='relationships')
    op.drop_table('relationships')
    op.drop_index('ix_asset_value', table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
