from typing import Literal

from pydantic import BaseModel, Field
from app.core.enums import AIIntent

from app.core.enums import (
    AssetStatus,
    AssetType,
)


# ============================================================
# Request
# ============================================================



# ============================================================
# Asset Filters
# ============================================================

class AssetFilters(BaseModel):
    """
    Supported asset filters.

    These are the ONLY filters the LLM
    is allowed to generate.
    """

    type: AssetType | None = None

    status: AssetStatus | None = None

    source: str | None = None

    tag: str | None = None

    value_contains: str | None = None


# ============================================================
# Sorting
# ============================================================

class SortOptions(BaseModel):
    """
    Sorting configuration.
    """

    field: Literal[
        "value",
        "created_at",
        "updated_at",
        "last_seen",
    ] = "last_seen"

    order: Literal[
        "asc",
        "desc",
    ] = "desc"



# ============================================================
# Structured LLM Output
# ============================================================

class AssetQuery(BaseModel):
    """
    Structured output generated by the LLM.

    This object is converted into
    a SQLAlchemy query.
    """

    filters: AssetFilters = Field(
        default_factory=AssetFilters,
    )

    sort: SortOptions = Field(
        default_factory=SortOptions,
    )

    limit: int = Field(
        default=100,
        ge=1,
        le=100,
        description="Maximum number of returned assets.",
    )


# ============================================================
# Intent Detection
# ============================================================

class IntentResponse(BaseModel):
    """
    Structured intent returned by the LLM.
    """

    intent: AIIntent


class RiskAnalysis(BaseModel):
    risk_level: str
    summary: str
    findings: list[str]
    recommendations: list[str]

class AssetEnrichment(BaseModel):
    """
    Structured enrichment generated by the LLM.
    """

    environment: str

    category: str

    criticality: str

    summary: str

class ReportAnalysis(BaseModel):
    """
    Structured report generated by the LLM.
    """

    report: str